### ISSUE TITLE
KeyError: 'code'

### ISSUE THREAD

**Issue by Singularity0909** [KivenCkl/LeetCode_Helper#4]
```python
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    Main().update()
  File "/Users/2U/OpenSource/LeetCode/Helper/helper/main.py", line 19, in update
    self.problems.update()
  File "/Users/2U/OpenSource/LeetCode/Helper/helper/problems.py", line 238, in update
    self.storeSubmissions()
  File "/Users/2U/OpenSource/LeetCode/Helper/helper/problems.py", line 207, in storeSubmissions
    s = SubmissionNode(submission)
  File "/Users/2U/OpenSource/LeetCode/Helper/helper/node.py", line 99, in __init__
    self.code = self.__formCode(json_data['code'])
KeyError: 'code'
```

**Comment by lryong** [comment]
Also encounter this problems,  seems no code field in the crawl results
