### ISSUE TITLE
题目爬虫出错

### ISSUE THREAD

**Issue by Singularity0909** [KivenCkl/LeetCode_Helper#5]
Traceback (most recent call last):
  File "/Users/2U/OpenSource/LeetCode/Helper/helper/problems.py", line 118, in __getProblemDesc
    return await resp.json()
  File "/Users/2U/.conda/envs/masterpiece/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1031, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://leetcode-cn.com/graphql')

通过切换力扣做题进度或者力扣账号可以避免这个报错，说明爬虫处理不了我提交过的某些题目。

**Comment by Singularity0909** [comment]
今天早些时候爬虫成功了，此后没有新的提交记录，下午重新爬虫时发现报错。

**Comment by Singularity0909** [comment]
感谢 @KivenCkl
